### ISSUE TITLE
panos_export

### ISSUE THREAD

**Issue by mrichardson03** [mrichardson03/mrichardson03.panos#30]
## Use cases

- Export files from device.

## Documentation

```
DOCUMENTATION = '''
---
module: panos_export
short_description: Export files from a PAN-OS device.
description:
    - Export files from a PAN-OS device.
author:
version_added: '1.0.0'
requirements:
    - xmltodict
notes:
    - Check mode is NOT supported.
    - Panorama is supported.
options:
    category:
        description:
            - Element type to export.
        type: str
        choices:
            - application-block-page
            - application-pcap
            - captive-portal-text
            - certificate
            - configuration
            - credential-block-page
            - credential-coach-text
            - data-filter-block-page
            - device-state
            - dlp-pcap
            - file-block-continue-page
            - file-block-page
            - filter-pcap
            - global-protect-portal-custom-help-page
            - global-protect-portal-custom-home-page
            - global-protect-portal-custom-login-page
            - global-protect-portal-custom-welcome-page
            - mfa-login-page
            - safe-search-block-page
            - ssl-cert-status-page
            - ssl-optout-text
            - stats-dump
            - tech-support
            - threat-pcap
            - url-block-page
            - url-coach-text
            - virus-block-page
        default: 'configuration'
    certificate_name:
        description:
            - Name of the certificate to export.
        type: str
    certificate_format:
        description:
            - Format for the certificate.
        type: str
        choices:
            - pem
            - pkcs10
            - pkcs12
    certificate_include_keys:
        description:
            - Whether to include the private key in the export.
        type: bool
        default: False
    certificate_passphrase:
        description:
            - Passphrase used to encrypt the certificate and/or private key.
        type: str
    filename:
        description:
            - Local path to output file (if any).
        type: str
    application_pcap_name:
        description:
            - When I(category=application-pcap), this can be a blank string, a packet capture directory name,
              or a packet capture name.  If the value is either blank or a directory name, a list of directories or
              packet capture files will be returned.  If the value is a packet capture file name, the file will be
              written to I(filename).
        type: str
    dlp_pcap_name:
        description:
            - When I(category=dlp-pcap), this value can be a blank string, or a packet capture name.  If the value
              is blank, a list of packet capture files will be returned.  If the value is a packet capture file name,
              the file will be written to I(filename).
        type: str
    dlp_password:
        description:
            - Password used to decrypt DLP packet capture.
        type: str
    filter_pcap_name:
        description:
            - When I(category=filter-pcap), this value can be a blank string, or a packet capture name.  If the
              value is blank, a list of packet capture files will be returned.  If the value is a packet capture file
              name, the file will be written to I(filename).
        type: str
    threat_pcap_id:
        description:
            - When I(category=threat-pcap), this value is a unique identifier for the packet capture, and can be
              obtained from the 'pcap_id' field in the THREAT log.
        type: str
    threat_pcap_search_time:
        description:
            - When I(category=threat-pcap), this value is is used to narrow the search for the 'pcap_id' and is
              used to set a time window in the range -5 minutes to +2 hours of the time specified. The search time is
              typically set to the **receive_time** field in the THREAT log. The PAN-OS log time string format is used,
              for example '2015/01/20 10:51:09'.  If the value is not specified, it will be set to the threat epoch time
              which is part of the 'pcap_id'.
        type: str
    threat_pcap_serial:
        description:
            - When I(category=threat-pcap), this value is required when exporting from Panorama and is used to
              specify the device to fetch the packet capture from.
        type: str
    timeout:
        description:
            - When category is set to 'tech-support', 'stats-dump', or 'device-state', the operating can take a while
              to complete.  This is the maximum amount of time to wait, in seconds.
        type: int
        default: 600
'''

EXAMPLES = '''
- name: Export configuration
  panos_export:
    category: 'configuration'
    filename: 'running-config.xml'

- name: Export application block page
  panos_export:
    category: 'application-block-page'
    filename: 'application-block-page.html'

- name: Export tech support (module will wait until file is ready)
  panos_export:
    category: 'tech-support'
    filename: 'tech-support.tgz'

- name: Export threat packet capture
  panos_export:
    category: 'threat-pcap'
    threat_pcap_id: '1206450340254187521'
    threat_pcap_search_time: '2020/07/20 18:20:19'
    filename: 'threat.pcap'
'''

RETURN = '''
msg:
    description: A string with an error message, if any.
    returned: failure, always
    type: str
stdout:
    description: If the output gives a directory listing, give the listing as JSON formatted string
    returned: success
    type: str
    sample: "{'dir-listing': {'file': ['/capture-rx', '/capture-tx', '/capture-fw']}}"
stdout_xml:
    description: If the output gives a directory listing, give the listing as XML formatted string
    returned: success
    type: str
    sample: "<dir-listing><file>/capture-rx</file><file>/capture-tx</file><file>/capture-fw</file></dir-listing>"
'''
```
